### PR TITLE
Add JSON report

### PR DESCRIPTION
**Pull request by julian776**
This pull request adds the JSON report feature.

#45

### CODE REVIEW

**Comment by julian776** [comment]
@Halleck45 Fixed

**Comment by Halleck45** [comment]
Thanks for your contribution! I've been a bit busy lately. I'll test it out as soon as I can and get back to you.

Thanks again for your help!

**Comment by Halleck45** [comment]
@julian776 I've added commits to your PR https://github.com/julian776/ast-metrics/pull/1

Can you (if you're agree) accept these modifications, then rebase your Pull Request ?

**Comment by Halleck45** [comment]
Thanks for your efforts @julian776, that's a great first contribution  :clap:  !

**Pull request merged**
